version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: dn-customers-backend
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test

volumes:
  mongodb:
